extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - plugin:lit/recommended
plugins:
  - "@typescript-eslint"
  - lit
parser: "@typescript-eslint/parser"
env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  "prettier/prettier":
    - error
    - singleQuote: true
      semi: false
      trailingComma: none
      arrowParens: avoid
