extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:lit/recommended
  - plugin:prettier/recommended
env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  "prettier/prettier":
    - error
    - singleQuote: true
      semi: false
      trailingComma: none
      arrowParens: avoid
